backend:
  name: git-gateway
  repo: Block-Digital-Team/client-newlifechurch
  branch: master

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Events Page"
        name: "events"
        file: "/content/events/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Header, name: header, widget: string}
          - {label: "Featured Events", name: featuredEvents, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Title", name: "title", widget: "text"},
              {label: Description, name: "description", widget: "text"} ]}
          - {label: "More Events", name: moreEvents, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"} ]}