<<<<<<< HEAD
version https://git-lfs.github.com/spec/v1
oid sha256:7ec479a55d7ff762a64f66b35946e25a98bcc75eb3e26b839a6e25ba46ac52e5
size 1466
=======
backend:
  name: git-gateway
  branch: master

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Pages"
    name: "pages"
    format: "json-frontmatter"
    files:
      - label: "Events"
        name: "events"
        file: "content/events/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Header, name: header, widget: string}
          - {label: "Featured Events", name: featuredEvents, widget: list, fields: [
            {label: "Image", name: "image", widget: "image"},
            {label: "Title", name: "title", widget: "text"},
            {label: "Description", name: "description", widget: "text"}]}
          - {label: "More Events", name: moreEvents, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"}]}
      - label: "Homepage"
        name: "homepage"
        file: "content/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Homepage Slider", name: homepageSlider, widget: list, fields: [
            {label: "Image", name: "image", widget: "image"},
            {label: "Link", name: "link", widget: "text"}]}
>>>>>>> 6ed2a91578f4b930557015d928811c7208614c54
